stages:
  eda:
    cmd: python bin/eda.py grn.input_dir=in_silico grn.edge_list=gold_standard.csv
    deps:
    - conf/config.yaml
    - conf/grn/in_silico.yaml
    - conf/experiment_tracking/docker.yaml
    - data/preprocessed/in_silico/gold_standard.csv
    - bin/eda.py
    outs:
    - data/out/in_silico/eda/graph.png
    - data/out/in_silico/eda/metrics.csv
  process:
    cmd: python bin/process.py grn.input_dir=in_silico grn.feature_matrix=expression_data.csv grn.edge_list=gold_standard.csv
    deps:
    - conf/config.yaml
    - conf/grn/in_silico.yaml
    - conf/experiment_tracking/docker.yaml
    - data/preprocessed/in_silico/expression_data.csv
    - data/preprocessed/in_silico/gold_standard.csv
    - bin/process.py
    outs:
    - data/out/in_silico/processed/expression_data.csv
    - data/out/in_silico/processed/gold_standard.csv
