defaults:
  - _self_
  - gnn: sage
  - grn: in_silico
  - db: graph
  - experiment_tracking: docker

experiment:
  name: nextflow_graph_machine_learning
  
dir:
  data_dir: data
  preprocessed_dir: preprocessed
  processed_dir: processed
  out_dir: out
