defaults:
  - _self_
  - grn: in_silico
  - experiment_tracking: docker

experiment:
  name: nextflow_graph_machine_learning
  
dir:
  data_dir: data
  preprocessed_dir: preprocessed
  out_dir: out
